import { useState } from 'react';

import Head from 'next/head';

// Components
import Markdown from '../components/Markdown';
import Sidebar from '../components/Sidebar';
import Navbar from '../components/Navbar';

export default function Home() {
  const [currentMarkdown, setCurrentMarkdown] = useState([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [content, setContent] = useState('');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        {isSidebarOpen && (
          <Sidebar
            currentMarkdown={currentMarkdown}
            setCurrentMarkdown={setCurrentMarkdown}
          />
        )}

        <div className="w-full flex-shrink-0">
          <Navbar
            isSidebarOpen={isSidebarOpen}
            currentMarkdown={currentMarkdown}
            setIsSidebarOpen={setIsSidebarOpen}
          />

          <main className="w-full">
            <Markdown
              content={content}
              setContent={setContent}
              currentMarkdown={currentMarkdown}
              setCurrentMarkdown={setCurrentMarkdown}
            />
          </main>
        </div>
      </div>
    </div>
  );
}
